"""Cut reference contact sheets into separate PNGs; no new drawing or background cleanup.

Masters are generated by built-in Codex image_gen. The crops are NOT native-ready assets.
Run with Python 3 + Pillow. The source masters are never modified.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent
ASSETS = ROOT / "assets"
SHEETS = {
    "portraits-a": ("sheet-portraits-a.png", (1024, 1536)),
    "portraits-b": ("sheet-portraits-b.png", (1254, 1254)),
    "fullbody": ("sheet-fullbody.png", (1024, 1536)),
}
PORTRAITS = {
    "welcome": ("portraits-a", 0, 0, "Before any blocking; a small greeting"),
    "ready": ("portraits-a", 1, 0, "Attentive before manual Start focus"),
    "focused": ("portraits-a", 0, 1, "Only after a confirmed active session"),
    "reflection": ("portraits-a", 1, 1, "Quiet consideration; no automatic break promise"),
    "finished": ("portraits-b", 0, 0, "Only after a verified focus end"),
    "recovered": ("portraits-b", 1, 0, "After successful free Restore access"),
    "needs-action": ("portraits-b", 0, 1, "Uncertain, permission or location needs attention"),
    "failed": ("portraits-b", 1, 1, "Actionable error, no shame"),
}
FULLBODY = {
    "welcome": ("fullbody", 0, 0, "Small wave; skirt visible"),
    "ready": ("fullbody", 1, 0, "Hands clasped before manual start; skirt visible"),
    "focused": ("fullbody", 0, 1, "Confirmed active session; skirt visible"),
    "recovered": ("fullbody", 1, 1, "Free restore verified; skirt visible"),
}


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


sources = {}
for key, (file_name, expected_size) in SHEETS.items():
    with Image.open(ASSETS / file_name) as sheet:
        assert sheet.size == expected_size, (file_name, sheet.size)
        assert sheet.mode in ("RGBA", "LA", "P"), (file_name, sheet.mode)
    sources[key] = {"path": f"assets/{file_name}", "sha256": sha(ASSETS / file_name), "size": list(expected_size)}


def render(states: dict, category: str) -> dict:
    result = {}
    for name, (source_key, column, row, note) in states.items():
        source = Image.open(ASSETS / SHEETS[source_key][0]).convert("RGBA")
        width, height = source.size
        box = (column * width // 2, row * height // 2, (column + 1) * width // 2, (row + 1) * height // 2)
        # Sheet A's left-panel wave lightly crosses the center seam; trim only the right cells' unused gutter.
        if source_key == "portraits-a" and column == 1:
            box = (box[0] + 24, box[1], box[2], box[3])
        image = source.crop(box)
        if image.getchannel("A").getbbox() is None:
            raise ValueError(f"empty alpha cell: {name}")
        target = ASSETS / category / f"{name}.png"
        image.save(target, optimize=True)
        result[name] = {"path": str(target.relative_to(ROOT)), "source": source_key, "cell": [column, row], "crop": list(box), "size": list(image.size), "sha256": sha(target), "meaning": note}
    return result


manifest = {
    "name": "Offzone Rue v6 — fresh state-reference study",
    "status": "selected visual direction; design reference only, not native-ready or store-published",
    "generationMode": "Codex built-in image_gen; no image_gen.py or direct API/CLI fallback",
    "editTarget": "../2026-09-24-rue-short-skirt/assets/anchor.png",
    "anchor": {"path": "assets/anchor-v6.png", "sha256": sha(ASSETS / "anchor-v6.png"), "size": [1024, 1536], "origin": "byte copy of user-selected v6"},
    "sessions": {"portraits-a": "01a0d220-5ae5-77f0-8da3-000515405f16", "portraits-b": "01a0d221-cc87-7553-8494-0a9cfe6378ef", "fullbody": "01a0d223-a854-7f20-a157-493291ded481"},
    "masters": sources,
    "portraits": render(PORTRAITS, "portraits"),
    "fullbody": render(FULLBODY, "fullbody"),
    "kiwiComparison": {"path": "assets/kiwi-current.svg", "sha256": sha(ASSETS / "kiwi-current.svg")},
    "alphaCaveat": "All generated images have alpha pixels, but portraits-a retains a smoky colored backdrop, portraits-b has vivid edge fringes, and fullbody has a halo. No production-clean alpha or dark-surface legibility is established.",
    "nativeApplied": False,
    "storePublished": False,
}
(ROOT / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
print("8 new portrait crops + 4 new full-body crops, from 3 generated masters; manifest written. Not native-ready.")
